### ISSUE TITLE
Action required on archived repository

### ISSUE THREAD

**Issue by ddemange** [tandriamil/BrFAST#1]
Dear Nampoina,

I'd like to ask you to delete the archived repository where you store a lot of teaching material from ISTIC.
Students are currently reusing your code, and this is not satisfactory (to say the least).

Currently, the repo is archived, but still visible, and read-only.

Could you please remedy this problem ?

Thanks,
Delphine

**Comment by tandriamil** [comment]
Dear Delphine,

I used GitHub to work on my projects and homeworks when I was still a student. After graduating, I left everything as is: the last commit dates back to june 2017 when I added a README explaining why I left it as is, and that I can remove the repos on demand.

Sadly, I suppose that students are copy-pasting them. As you asked, I deleted the repositories related to the courses and tutorials given at ISTIC.

Have a nice day,
Nampoina
